language: python
node_js:
  - "0.10.25"
before_install:
  - npm install -g jshint
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: flake8 apps/