# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Match')),
                ('time', models.TimeField(verbose_name='Time of Match')),
                ('teamonescore', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Team One Goals')),
                ('teamtwoscore', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Team Two Goals')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='teamone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_teamone', to='venues.Team', verbose_name='Team One'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamtwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_teamtwo', to='venues.Team', verbose_name='Team Two'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.Venue', verbose_name='Venue'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set([('date', 'venue')]),
        ),
    ]
